#!/bin/bash
# Script para facilitar desenvolvimento com a nova estrutura

echo "🎯 Falcons - Estrutura Backend/Frontend Organizada"
echo "=================================================="
echo ""

# Mostrar estrutura
echo "📁 Estrutura do Projeto:"
echo ""
echo "src/"
echo "├── frontend/          # 🎨 Interface e componentes"
echo "│   ├── app/          # Pages e layout Next.js"
echo "│   ├── components/   # Componentes reutilizáveis"
echo "│   ├── hooks/        # Custom React hooks"
echo "│   └── types/        # Tipos TypeScript do frontend"
echo "│"
echo "├── backend/           # 🔧 Lógica de servidor"
echo "│   ├── api/          # API routes (/api/*)"
echo "│   ├── services/     # Lógica de negócio"
echo "│   ├── db/           # Queries de banco de dados"
echo "│   └── lib/          # Supabase e utilitários"
echo "│"
echo "└── shared/            # 📦 Código compartilhado"
echo "    ├── lib/          # Utilitários gerais"
echo "    └── types/        # Tipos compartilhados"
echo ""
echo "=================================================="
echo ""
echo "✅ Benefícios da Nova Estrutura:"
echo "   • Separação clara de responsabilidades"
echo "   • Frontend não misturado com lógica de servidor"
echo "   • Fácil localizar código"
echo "   • Melhor organização para crescimento"
echo "   • Imports mais semânticos"
echo ""
echo "🚀 Próximos Passos:"
echo "   1. Criar hooks em frontend/hooks/ para data fetching"
echo "   2. Organizar serviços em backend/services/"
echo "   3. Estruturar API routes em backend/api/"
echo "   4. Consolidar types em shared/types/"
echo "   5. Leia os arquivos: ESTRUTURA.md e GUIA_IMPORTS.md"
echo ""
